stages:
  - build
  - syntax
  - lint
 
ci_container_build:
  stage: build
  script:
    - docker --version
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -f Dockerfile.CICD -t ${CI_REGISTRY_IMAGE} .
    - docker push ${CI_REGISTRY_IMAGE}

check_ansible_syntax:
  stage: syntax
  script:
    - ansible-playbook -i inventory/gside/foundation.ini site.yml --syntax
  tags:
    - runner-efes

check_ansible_lint_plybook:
  stage: lint
  script:
    - ansible-lint -c ../.ansible-lint -v --show-relpath -f pep8 --nocolor site.yml
  tags:
    - runner-efes

check_ansible_lint_group_vars:
  stage: lint
  script:
    - ansible-lint -c ../.ansible-lint -v --show-relpath -f pep8 --nocolor group_vars/*
  tags:
    - runner-efes

check_ansible_lint_host_vars:
  stage: lint
  script:
    - ansible-lint -c ../.ansible-lint -v --show-relpath -f pep8 --nocolor host_vars/*
  tags:
    - runner-efes

check_ansible_lint_inventory:
  stage: lint
  script:
    - ansible-lint -c ../.ansible-lint -v --show-relpath -f pep8 --nocolor inventory/*
  tags:
    - runner-efes
