--- # MariaDB バックアップスクリプト配置タスク
### 事前タスク
- name: setup OS varibleds
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ os_version }}.yml"
    - "vars/{{ ansible_os_family }}.yml"

- name: 作業用ディレクトリの作成
  ansible.builtin.include_tasks: roles/01-file_Recovery/tasks/1pre_mkdir.yml
### 事前タスク END

- name: バックアップスクリプを格納ディレクトリ作成
  ansible.builtin.file:
    path: "{{ work_dir }}"
    mode: "700"
    state: directory
    recurse: false

- name: スクリプト格納ディレクトリの確認
  ansible.builtin.stat:
    path: "{{ work_dir }}"
  register: check_dir

- name: メンテナンススクリプト設定
  when: check_dir.stat.exists
  block:
    - name: メンテナンスファイル転送
      ansible.builtin.template:
        src: "{{ item.local_file }}"
        dest: "{{ item.remote_file }}"
        owner: "{{ item.own }}"
        group: "{{ item.gro }}"
        mode: "{{ item.mod }}"
      with_items: "{{ mv_work_script }}"
      register: cp_result

    - name: 機密ファイル転送
      ansible.builtin.template:
        src: secret.conf.j2
        dest: /root/.work.d/.secret.conf
        owner: root
        group: root
        mode: "0600"
      no_log: true
      register: cp_result

# - ansible.builtin.debug: var=cp_result

### バックアップメンテナンス設定 END

### 事後タスク
- name: 作業結果を回収
  ansible.builtin.include_tasks: roles/01-file_Recovery/tasks/2post_Recovery.yml
### 事後タスク END
