---
### SSHリモート接続
ansible_ssh_private_key_file: ~/.ssh/master.ecdsa.key
ansible_ssh_port: "{{ sshd_port }}"
ansible_ssh_user: daath
sshd_port: 52002
gitlab_ssh_port: "{{ sshd_port }}"

# 管理ユーザーへの接続拡張認証公開鍵登録ファイル
ex_auth_keys: ".ssh/extend_authorized_keys"
# サーバ間バックアップ認証用公開鍵登録ファイル(設定パスは各ロールで行う)
bk_auth_keys: ".ssh/backup_authorized_keys"

### 特権ユーザ
ansible_become_pass: "{{ vault_become_pass }}"

### 実行日
sirial_date: "{{ lookup('pipe', 'date +%y%m%d%H%M') }}"
run_date: "{{ lookup('pipe', 'date +%Y%m%d-%H') }}"
new_date: "{{ lookup('pipe', 'date +%Y') }}"

### OSのバージョン変数 格納されるのはRHEL8なら「RedHat8」
os_version: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"
