---
### SSHリモート接続
ansible_ssh_port: "{{ sshd_port }}"
sshd_port: 22

# 管理ユーザーへの接続拡張認証公開鍵登録ファイル
ex_auth_keys: ".ssh/extend_authorized_keys"

### 実行日
sirial_date: "{{ lookup('pipe', 'date +%y%m%d%H%M') }}"
run_date: "{{ lookup('pipe', 'date +%Y%m%d-%H') }}"
new_date: "{{ lookup('pipe', 'date +%Y') }}"

### OSのバージョン変数 格納されるのはRHEL8なら「RedHat8」
os_version: "{{ ansible_distribution }}{{ ansible_distribution_major_version }}"
