---
### == 事前タスク
- name: "set {{ os_version }} OS varibleds"
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ os_version }}.yml"
    - "vars/{{ ansible_os_family }}.yml"

- name: 作業ディレクトリ作成
  ansible.builtin.include_tasks: roles/file_Recovery/tasks/1pre_mkdir.yml
### == 事前タスク END

### == 標準リポジトリ設定

- name: RHEL系-標準リポジトリの設定
  ansible.builtin.include_tasks: include/base.yml
  tags: task_base
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'

### == 標準リポジトリ設定 END

### == 拡張リポジトリ設定

- name: RHEL系-拡張リポジトリの設定
  ansible.builtin.include_tasks: include/eXpansion.yml
  tags: task_ex
  when: ansible_os_family == "RedHat"

### == 拡張リポジトリ設定 END

### == 事後タスク
- name: ファイル回収
  ansible.builtin.include_tasks: roles/file_Recovery/tasks/2post_Recovery.yml
### == 事後タスク END
