---
# tasks file for mariadb

### 事前タスク
- name: setup OS varibleds
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "vars/{{ os_version }}.yml"
    - "vars/{{ ansible_os_family }}.yml"

- name: フォルダ回収先の作成
  ansible.builtin.include_tasks:
    file: roles/01-file_Recovery/tasks/1pre_mkdir.yml
### 事前タスク END

#### MariaDBインストール

- name: MariaDBインストール
  ansible.builtin.include_tasks:
    file: "include/{{ os_version }}.yml"
  tags: task_install

### MariaDB設定

- name: MariaDB 基本設定
  ansible.builtin.include_tasks:
    file: include/setup_conf.yml
  tags: task_conf

- name: MariaDB データベース初期設定
  ansible.builtin.include_tasks:
    file: include/initdb.yml
  tags: task_setup

### 事後タスク
- name: ファイル回収タスク
  ansible.builtin.include_tasks:
    file: roles/01-file_Recovery/tasks/2post_Recovery.yml
### 事後タスク END

### 事後確認
- name: MariaDB Gossる
  ansible.builtin.include_tasks:
    file: include/goss.yml
  tags: task_goss
