---
# vars/RedHat8 file for mariadb

### インストール設定
mariadb_pack:
 - "@mariadb:{{ mariadb_Ver }}"
 - python3-PyMySQL

# DBソケット
db_unix_sock: /var/lib/mysql/mysql.sock

### 設定ファイル一覧
server_cnf: /etc/my.cnf.d/mariadb-server.cnf
client_cnf: /etc/my.cnf.d/client.cnf
mariadb_syslog_cnf: /etc/logrotate.d/mariadb

### MariaDB server 設定ファイル
mv_db_conf:
 - { local_file: "{{ os_version }}/mariadb-server.cnf.j2", remote_file: "{{ server_cnf }}", own: root, gro: root, mod: 644 }
 - { local_file: "{{ os_version }}/client.cnf.j2", remote_file: "{{ client_cnf }}", own: root, gro: root, mod: 644 }
 - { local_file: "{{ os_version }}/mariadb_logrota.j2", remote_file: "{{ mariadb_syslog_cnf }}", own: root, gro: root, mod: 644 }
