--- ### roles/repo_cli/vars/CentSO7
### == 作業対象ファイル
base_repo_path: /etc/yum.repos.d/CentOS-Base.repo

epel_repo_path: /etc/yum.repos.d/epel.repo
elrepo_repo_path: /etc/yum.repos.d/elrepo.repo
sclo_repo_path: /etc/yum.repos.d/CentOS-SCLo-scl.repo
sclo_rh_repo_path: /etc/yum.repos.d/CentOS-SCLo-scl-rh.repo

### == Discript

### == リポジトリファイル編集
base_repo_list:
 - { path: "{{ base_repo_path }}", sec: base, opt: "baseurl", val: "{{ local_base_url }}" }
 - { path: "{{ base_repo_path }}", sec: base, opt: "exclude", val: "php* ansible*" }
 - { path: "{{ base_repo_path }}", sec: updates, opt: "baseurl", val: "{{ local_base_updates_url }}" }
 - { path: "{{ base_repo_path }}", sec: updates, opt: "exclude", val: "php* ansible*" }
 - { path: "{{ base_repo_path }}", sec: extras, opt: "baseurl", val: "{{ local_base_extras_yum_url }}" }
 - { path: "{{ base_repo_path }}", sec: extras, opt: "exclude", val: "php* ansible*" }

ex_repo_list:
 - { path: "{{ epel_repo_path }}", sec: epel, opt: "baseurl", val: "{{ local_epel_url }}" }
 - { path: "{{ epel_repo_path }}", sec: epel, opt: "enabled", val: "0" }
 - { path: "{{ sclo_repo_path }}", sec: centos-sclo-sclo, opt: "baseurl", val: "{{ local_scl_url }}" }
 - { path: "{{ sclo_repo_path }}", sec: centos-sclo-sclo, opt: "mirrorlist", val: "{{ scl_org_yum_url }}" }
 - { path: "{{ sclo_repo_path }}", sec: centos-sclo-sclo, opt: "enabled", val: "0" }
 - { path: "{{ sclo_rh_repo_path }}", sec: centos-sclo-rh, opt: "baseurl", val: "{{ local_scl_rh_url }}" }
 - { path: "{{ sclo_rh_repo_path }}", sec: centos-sclo-rh, opt: "mirrorlist", val: "{{ scl_rh_org_yum_url }}" }
 - { path: "{{ sclo_rh_repo_path }}", sec: centos-sclo-rh, opt: "enabled", val: "0" }
 - { path: "{{ elrepo_repo_path }}", sec: elrepo, opt: "baseurl", val: "{{ local_elrepo_url }}" }
 - { path: "{{ elrepo_repo_path }}", sec: elrepo, opt: "enabled", val: "0" }

### == 追加リポジトリーパッケージ
remi_repo_rpm: remi-release-7.rpm

repo_pack:
 - epel-release
 - elrepo-release
 - centos-release-scl-rh
 - centos-release-scl
