name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Registry
        run: echo ${{ secrets.CI_REGISTRY_PASSWORD }} | docker login ${{ secrets.CI_REGISTRY }} -u ${{ secrets.CI_REGISTRY_USER }} --password-stdin
      - name: Build Docker image
        run: docker build -f Dockerfile.CICD -t ${{ secrets.CI_REGISTRY_IMAGE }} .
      - name: Push Docker image
        run: docker push ${{ secrets.CI_REGISTRY_IMAGE }}

  check_ansible_syntax:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: pip install ansible
      - name: Check Ansible syntax
        run: ansible-playbook -i inventory/gside/foundation.ini site.yml --syntax-check

  check_ansible_lint_playbook:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible Lint
        run: pip install ansible-lint
      - name: Lint playbook
        run: ansible-lint -c ../.ansible-lint -v --show-relpath -f pep8 --nocolor site.yml

  check_ansible_lint_group_vars:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible Lint
        run: pip install ansible-lint
      - name: Lint group_vars
        run: ansible-lint -c ../.ansible-lint -v --show-relpath -f pep8 --nocolor group_vars/*

  check_ansible_lint_host_vars:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible Lint
        run: pip install ansible-lint
      - name: Lint host_vars
        run: ansible-lint -c ../.ansible-lint -v --show-relpath -f pep8 --nocolor host_vars/*

  check_ansible_lint_inventory:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install Ansible Lint
        run: pip install ansible-lint
      - name: Lint inventory
        run: ansible-lint -c ../.ansible-lint -v --show-relpath -f pep8 --nocolor inventory/*
